language: python

python:
    - 2.7
    - 3.4
    - 3.5

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:

        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - SETUP_CMD='test'
        - MAIN_CMD='python setup.py'
        - PIP_DEPENDENCIES=''
        - CONDA_DEPENDENCIES='Cython shapely'

        # If there are matplotlib or other GUI tests, uncomment the following
        # line to use the X virtual framebuffer.
        - SETUP_XVFB=True

    matrix:
        # Make sure that egg_info works without dependencies
        - SETUP_CMD='egg_info'
        # Try all python versions with the latest numpy
        - SETUP_CMD='test'

matrix:
    include:

        # Do a coverage test in Python 2.
        - python: 2.7
          env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 3.5
          env: SETUP_CMD='build_sphinx -w'
               CONDA_DEPENDENCIES='Cython shapely wcsaxes'

        # Try Astropy development version
        - python: 2.7
          env: ASTROPY_VERSION=development
        - python: 3.5
          env: ASTROPY_VERSION=development

        # Python 3.3 doesn't have numpy 1.10 in conda, but it can be put
        # back into the main matrix once the numpy build is available in the
        # astropy-ci-extras channel (or in the one provided in the
        # CONDA_CHANNELS environmental variable).
        - python: 3.3
          env: SETUP_CMD='egg_info'
        - python: 3.3
          env: SETUP_CMD='test' NUMPY_VERSION=1.9

        # Try older numpy versions
        - python: 2.7
          env: NUMPY_VERSION=1.10
        - python: 2.7
          env: NUMPY_VERSION=1.9
        - python: 2.7
          env: NUMPY_VERSION=1.8
        - python: 2.7
          env: NUMPY_VERSION=1.7

        # Try numpy pre-release
        - python: 3.5
          env: NUMPY_VERSION=prerelease

        # Do a PEP8 test with pycodestyle
        - python: 3.5
          env: MAIN_CMD='pycodestyle regions --count' SETUP_CMD=''

    allow_failures:
        - python: 3.5
          env: NUMPY_VERSION=prerelease

install:

    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
   - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='regions/tests/coveragerc'; fi
